name: Run Discord Bot

on:
  workflow_dispatch:   # allow manual runs
  push:                # run on every push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f Hazsbot/requirements.txt ]; then
            pip install -r Hazsbot/requirements.txt
          elif [ -f DiscordBOT/requirements.txt ]; then
            pip install -r DiscordBOT/requirements.txt
          fi

      - name: Find and run bot (keeps process alive)
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          if [ -f main.py ]; then
            python main.py
          elif [ -f Hazsbot/main.py ]; then
            python Hazsbot/main.py
          elif [ -f DiscordBOT/main.py ]; then
            python DiscordBOT/main.py
          else
            echo "❌ Could not find main.py" && exit 1
          fi
        timeout-minutes: 9999
