name: Run Discord Bot

on:
  workflow_dispatch:   # run manually
  push:                # or whenever you push code

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: python main.py
