name: Run Discord Bot

on:
  workflow_dispatch:   # allow manual runs
  push:                # run on every push to any branch

jobs:
  run:
    runs-on: ubuntu-latest
    # Maximum run time for the job (in minutes). Adjust as needed — GitHub limits apply.
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Determine requirements file
        id: find-req
        run: |
          if [ -f requirements.txt ]; then
            echo "REQ=requirements.txt" >> $GITHUB_ENV
          elif [ -f Hazsbot/requirements.txt ]; then
            echo "REQ=Hazsbot/requirements.txt" >> $GITHUB_ENV
          elif [ -f DiscordBOT/requirements.txt ]; then
            echo "REQ=DiscordBOT/requirements.txt" >> $GITHUB_ENV
          else
            echo "REQ=" >> $GITHUB_ENV
          fi

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'Hazsbot/requirements.txt', 'DiscordBOT/requirements.txt') }}

      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -n "$REQ" ]; then
            python -m pip install --upgrade pip
            python -m pip install -r "$REQ"
          else
            echo "No requirements.txt found — skipping dependency installation"
          fi

      - name: Find and run bot
        env:
          # Map common secret names so your code can read any of them.
          DISCORD_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
          DISCORDBOTTOKEN: ${{ secrets.DISCORDBOTTOKEN }}
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
          TOKEN: ${{ secrets.TOKEN }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          echo "Starting Hazsbot..."
          if [ -f main.py ]; then
            python main.py
          elif [ -f Hazsbot/main.py ]; then
            python Hazsbot/main.py
          elif [ -f DiscordBOT/main.py ]; then
            python DiscordBOT/main.py
          else
            echo "❌ Could not find main.py" && exit 1
          fi
