name: Run Hazsbot

on:
  push:
    branches:
      - main
  workflow_dispatch:  # allows manual start from GitHub UI

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # Install dependencies

      # Run Hazsbot with secrets
      - name: Run Hazsbot
        env:
          DISCORDTOKEN: ${{ secrets.DISCORDTOKEN }}
          DEEPSEEKAPIKEY: ${{ secrets.DEEPSEEKAPIKEY }}
          PANEL_GUILD_ID: ${{ secrets.PANEL_GUILD_ID }}
          PANEL_OWNER_ID: ${{ secrets.PANEL_OWNER_ID }}
        run: |
          echo "Starting Hazsbot..."
          python main.py || echo "❌ Bot crashed with exit code $?"
